"""your message

Revision ID: 341d38da7462
Revises: 50eeec3eb543
Create Date: 2023-07-06 11:08:10.136513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341d38da7462'
down_revision = '50eeec3eb543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_artworks_style_id_styles'), 'styles', ['style_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_artworks_style_id_styles'), type_='foreignkey')
        batch_op.drop_column('style_id')

    op.drop_table('styles')
    # ### end Alembic commands ###
