"""your message

Revision ID: f142fc614739
Revises: abd7c83a9772
Create Date: 2023-07-05 15:19:34.994182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f142fc614739'
down_revision = 'abd7c83a9772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art_collections')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artwork_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_collections_artwork_id_artworks'), 'artworks', ['artwork_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collections_artwork_id_artworks'), type_='foreignkey')
        batch_op.drop_column('artwork_id')

    op.create_table('art_collections',
    sa.Column('artwork_id', sa.INTEGER(), nullable=False),
    sa.Column('collection_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], name='fk_art_collections_artwork_id_artworks'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name='fk_art_collections_collection_id_collections'),
    sa.PrimaryKeyConstraint('artwork_id', 'collection_id')
    )
    # ### end Alembic commands ###
